; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<main.cpp> +<lw3_2__led_button_tasks_freertos/>
lib_deps = 
	arduino-libraries/LiquidCrystal@^1.0.7
	chris--a/Keypad@^3.1.1
	feilipu/FreeRTOS@^11.1.0-3
